# Generated by Django 2.0.7 on 2018-07-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
