# Generated by Django 2.0.7 on 2018-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_auto_20180705_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='position',
        ),
        migrations.AddField(
            model_name='instructor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='instructors_images'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='instructors_images'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='name2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
