# Generated by Django 2.0.7 on 2018-07-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_auto_20180705_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructors_Row',
        ),
    ]
