# Generated by Django 2.0.7 on 2018-07-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0008_auto_20180705_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'default_permissions': ('change', 'delete')},
        ),
    ]
