# Generated by Django 2.0.7 on 2018-07-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0011_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'default_permissions': ('add', 'change')},
        ),
    ]
